# Generated by Django 2.2 on 2020-11-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakevaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiemphong',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tiemphong',
            name='create_by',
            field=models.CharField(default='doan', max_length=50),
        ),
    ]
