# Generated by Django 2.2 on 2020-11-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeoAll',
            fields=[
                ('rfid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Heocon'), ('2', 'Heome'), ('3', 'Heonai')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HeoMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_heome', models.CharField(blank=True, max_length=50, null=True)),
                ('rfid_heome', models.CharField(blank=True, max_length=50, null=True)),
                ('chuong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeoCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_heome', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('rfid_heocon', models.CharField(blank=True, max_length=50, null=True)),
                ('id_heome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakeheo.HeoMe')),
            ],
        ),
    ]
